if ENV['platform'] == 'linux'
	CFLAGS = "-I /usr/lib/erlang/lib/erl_interface-3.6.3/include -I /usr/lib/erlang/usr/include -fPIC -g -O2 -Wall"
  LDFLAGS = "-shared"
	EXTLIBDIRS = "-L /usr/lib -L /usr/lib/erlang/lib/erl_interface-3.6.3/lib"
	EXTLIBS = "-lei -llua"
else
	CFLAGS = "-I /opt/local/lib/erlang/erts-5.7.4/include -I /opt/local/var/macports/software/erlang/R13B03_0/opt/local/lib/erlang/lib/erl_interface-3.6.4/include -I /usr/local/lib/erlang/lib/erl_interface-3.6/include -I /LuaLibrary/src -fPIC -g -O2 -Wall"
  LDFLAGS = "-dynamic -bundle -undefined suppress -flat_namespace"
	EXTLIBDIRS = ""
  EXTLIBS = "/opt/local/lib/liblua.a /opt/local/lib/erlang/lib/erl_interface-3.6.4/lib/libei.a"

end

FILES = ["commands", "lua_drv"]

desc "Compile driver to a shared lib"
task :compile => ["../priv/lua_drv.so"]

FILES.each do |f|
  file "#{f}.o" => ["#{f}.c"] do
    # puts "gcc #{CFLAGS} -c -o #{f}.o #{f}.c"
    sh "gcc #{CFLAGS} -c -o #{f}.o #{f}.c"
  end
end

file "../priv/lua_drv.so" => FILES.map {|f| "#{f}.o"} do
  sh "mkdir -p ../priv"
  # puts "gcc #{CFLAGS} #{LDFLAGS} -o ../priv/lua_drv.so #{FILES.join('.o ')}.o #{EXTLIBS}"
  print "Compiling lua_drv.so..."
  sh "gcc #{CFLAGS} #{LDFLAGS} #{EXTLIBDIRS} -o ../priv/lua_drv.so #{FILES.join('.o ')}.o #{EXTLIBS}"
  print " done\n"
  #sh "rm #{FILES.join('.o ')}.o"
end

task :clean do
  sh "rm ../priv/*.so"
end
